name: CI

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Moon Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4
        with:
          auto-setup: true
          cache-base: ${{ github.event.repository.default_branch }}

      - name: Run Moon CI
        run: moon ci --summary minimal

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
        with:
          distribution: goreleaser
          version: v2.15.4
          args: check
